get:
  operationId: ConfigurationTypesGet
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            $ref: ../components/schemas/docType.yml
    '401':
      description: Not Authorized to get document
    '404':
      description: Document not found
  summary: List registered document type
  tags:
    - Configuration
