get:
  operationId: ConfigurationTypeDocumentGet
  parameters:
    - description: The name of the document type
      in: path
      name: docType
      required: true
      schema:
        type: string
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            $ref: ../components/schemas/docType.yml
    '401':
      description: Not Authorized to get document
    '404':
      description: Document not found
  summary: Document type description
  tags:
    - Configuration
